# datasource configs
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: root
    jdbc:
      url: jdbc:postgresql://localhost:5432/reportdb
  hibernate-orm:
    database:
      generation: update

  # quarkus http configs
  http:
    port: 8081

  # keycloak security configs
  oidc:
    auth-server-url: http://localhost:8180/realms/quarkus
    client-id: backend-service
    credentials:
      secret: secret

# Kafka configs
mp:
  messaging:
    incoming:
      proposal:
        connector: smallrye-kafka
        topic: proposal
      quotation:
        connector: smallrye-kafka
        topic: quotation
    connector:
      smallrye-kafka:
        bootstrap:
          servers: localhost:9092